apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:iwLtROFGXbPVflMLgQofsVtB7NCdZ3/HpomF9HOCL9aA0M3Hisckx71rQcYr4iJKTfo2BqLIeBjSYKyGcZ3rgOj/NYNeSzPumLhvfANOviu1MQi6I0jJutVMIKIIw13j8AL2bKuy7dK7HbjQHakyYCRHux9NCeC9kvC7s1Cf7E8oZfjvuhat5XQ18LoUqMT8x8DGcgOAPRyAv3Vr5tAPZoetCjOxL74MuJaSsIeJciw8ol4b8d6r6k2zhcbDm94ei+n2ShabrgeU7X0LBWKWzg9WCIfXmANi+Fsa6nMQCmYu/n1UGzIO+cZFw/3Wmp0M+VoKZgBmscW8os52g5/o2d4BkCZKmoiVgnwXGotspBO9SR9ZMXenCj6tyjXTX12mF0+5J1zDEgTDSTKF1RsQWTo8P1FYtKRMFrCr/+8sbLh4CcZPsB5VID/BWaweonq2VgUYuVH7eRN7impwL94uzL/Xh/hMiYied9FrAt1JDHns90C3vh398hAorqa5nH2LPam2PTxB997r/POM/rkdXDEv6XglQkpFFKb4mgsLCbiYF1Rotfw7VvxaUyEA8cUCtj6Jkg5rhzIhpeVQYndGuCZ5w0muaRH/lhcsc1goGwYKSwoF3lzcEZ24rLD+G9H/FaiCuqdzzfBGfbO4TqJ0LsY17PlfoNkOazkQJckUHZivfldyKyWB57+u+t3/raMiZ4pzw74i8Z33hWPu5TDyt51DPZOdUyhNcquOYEFjm1tFsQ/ufoRF36lnc/rbJs8pL1KOk8X/Kh4hzVMuQX+FlwHHlfEobfLYXIFx6twkxCeVbUO8NFBQnZElpERppCpUsZBnRP144goWCkymRK/LXQFsIzU9xzX0aVfYqw+uPgjFSFTEIGJmuWUZ+sHDSCUcWsfBBBkGWt09jRrsyuWRNYo6th3zLJMXLBAxVwmTIpov2RrpKlFi5F8/mbrZrloWMcbsF3pX1H1fOnE0ILa/i6CtIFkX6zDKjdkLD0XPq2lyCiiTwLIDmbQyDgLN8RAzEZd7JlkWkJk+3F4fyD6hTY5FBLD/gWP3q5s1Se7LzBN4hflV/6GoeAzONYQZkdRnV5RcGP3DSWzKype+Kttn+zeK0PiKbLgC4D1f34yC,iv:tiVzZUPrW3JZJUBnW3c5KAZyWIPVKebYQiDsIx/qj/M=,tag:KfW/lHNgMVCCb2pLNP+twA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdDlTcGJRRkJ3ZDdCeVJn
            Y3djMVIwSHZVSGIvcHEwWDNVM0lkMWcvTndJCmQwbUhXRnVlUmN3OTRuVldESWtU
            VFJMQ2E1OWVDNllhSld5d1c2cWxxK1UKLS0tIG9WUWtKZXBOamdoM0ZsMEJZcFcz
            eVBDVlhCZkFxbTdXNUZ6K2RPOGxjejgKn6X/zKzCn468LDLqcXSk22+hv/n6rk+r
            +PaZsDym3cZwrjENp680WTGdiNZ7vFWpnH6FuhGOUP45WdQ8YSF4zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T02:12:49Z"
    mac: ENC[AES256_GCM,data:1AE9bFt9UO8q06eRBWO4KLpWQNvKuCPOACcPtxnSUe+sVTkegBGjbHDI0uxr3UvhthnhnAv9d307lSz4rzzOpMPlTRWjmTPb+YFDNXlSi/nIuohN3VZdTDVlJOnVGLeY6y3RJS9Z4M0QovA0z2zCQjIPaMRYq0UBCRgTOMPGVUE=,iv:42els4OgrNP3oRYrolRrsXFVBxFNwvxtjct+bmJ4Oos=,tag:EgUJAeKJY3cEjcX4OkwkpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
