apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:l/t091Kll47TAlADH1s=,iv:vf1/cm0Hat9fCytc8aJgILsAwUMVMB9L8kYRb7Pb2Yc=,tag:/RyeZ2KKU8DyWMdKiqVeww==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:0F13sFijCg==,iv:2A32zXrbv1zDudmbpcGwA5g2SUwxlrpVYDjSnup28CY=,tag:jXMXPtJWC03jWGHtUDoJbg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:NeZZms5SnS49yC3XhA==,iv:Hmlvo0pyfMoPMkr9HIZ/rAIwUr+I93X3EZzt0vJZT9o=,tag:3V/h69z5M+FsXEpSGC8cPA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iXzDKeFXf8r7QEkCLFw7qg==,iv:f4nt2kTU0N6JBYTji7+TfGtpvFcntYP6jbLq+BAHmwA=,tag:n9Sg+ee6dlQa3lAy3Qfm3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTnhBQ2ZKekc1c2Zkay82
            L2dhc3oxOE00WUc3MEo2dXlaUk1ST1RMSUhRClBGRjBZbVRvNVR1bFRKOEJISWVJ
            Z2xzWnNkYzFnTGl3aXNlM01UTDhHWFUKLS0tIHdaYjVadGpDejJtdTcvOHF5VCtQ
            bXRsY1d6Rk0xWXQvZFQxNmlhNTFHaEEKZfh1AnAu76B/+42QrGQabKK6bg/DxYAo
            chqkz57vEx5vXMdkDaK4xxw4RCPMhf9j+hcZTyJC1pg+hMcjlRAFuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T21:06:57Z"
    mac: ENC[AES256_GCM,data:gHDZGdqaVQ9rLHL6EcOCCYd6E0VT5cCLIauxUHr0e3bkLt8YEn2grVYa+jW13H5VREzAeHM8DQ0o99c6zb0eNC8AAvFdjl7H+yU+OhmaasJyC/P8OyRm5roKT/DdNjpugJjSlY/E7YaQv2KTZESErZH3LDwzMkO7OrPFqS/I+N0=,iv:OvbcvuoX4EAia+ndjKNDT9Nd2IIL/7xXiISQi3/VWy4=,tag:YfgCTlvgqbLxipcU6afm1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
