apiVersion: v1
kind: Secret
metadata:
    name: activepieces-secrets
    namespace: services
type: Opaque
stringData:
    AP_JWT_SECRET: ENC[AES256_GCM,data:lknK0eE+zvoIxVyp/7GRCg30iaICNclYis7fgBDbaz0YjswxEVSM0A9bArbtAVxDy9gR3ZtfRrhZLYxxfkHaFw==,iv:EdNf9zzd+3harxeWt0/6JTAyx3Gmx8W+4zq1G2I2GMQ=,tag:UXVqiS2t3dTPzqiFvzU/Xw==,type:str]
    AP_API_KEY: ENC[AES256_GCM,data:WyJAJ+7vrpP0XaNqv9b41fYeZV8uYvqQ6btV/N4niDoWKL62fBlkEEdoWlNWcJfcixUy3Nwkfmmz/szErnVPmUwuFr0GEnLFFbXkWwr+1nyBsvfVOVUZfdOBjXUKDzENXfqgSHqYFsXu10vK/JBGoEKafD5PolRO/MYeB1EwUOY=,iv:dwUugBlIvBW+T1Ma0xZF/An/wWvGsEBcYI/9ogdtHvI=,tag:kKvg5JeAn1oWKsfApJeZOQ==,type:str]
    AP_ENCRYPTION_KEY: ENC[AES256_GCM,data:Ojyuryt+u5bim2dIgLjl3idWhGNYfFzOWJazgINoWtw=,iv:LwmU+MXnbTUTPU045mXv1CwlBzwj379jsm8zU24FDgY=,tag:iDsvQp3hRDeTJ6eZOYI76w==,type:str]
    AP_REDIS_HOST: ENC[AES256_GCM,data:Q6iGCGA/nErKqP2JeBXeXoWOYUOf,iv:uhQbTxAX7epbXcMb2S4YraY9McQ1JdWmuVjRlLF+iJE=,tag:9hzHUtWiNYyWxNe4bZsw3w==,type:str]
    AP_REDIS_PORT: ENC[AES256_GCM,data:HvQSHA==,iv:vEZOj16oCS13AwLlwZtbbSdpPqzo71r17y3AGj/i7KU=,tag:qcWfawofVWpwvMjTEX4g2w==,type:str]
    AP_REDIS_DB: ENC[AES256_GCM,data:bg==,iv:33HEfrm//gcx/1AU5lHj8xWvLcU0hvXsP7BT68KeLMo=,tag:PcO62RzpQ5P/qB6BGZa+Tw==,type:str]
    AP_TELEMETRY_ENABLED: ENC[AES256_GCM,data:e9zrB1k=,iv:L1EwiRxPs/iPINEIEOxoBwPM9Uh82JRxz+bUSrqTPQQ=,tag:mMm4d5R9QbkBdHVFtBgucQ==,type:str]
    AP_POSTGRES_USERNAME: ENC[AES256_GCM,data:6oxke8shZJHEi5jH,iv:EOR24yZheyJqxfux1M1gHOhmJTtX53SXvdhhUawuSy8=,tag:tDP43J9A4zYdYHlhLp1p0Q==,type:str]
    AP_POSTGRES_PORT: ENC[AES256_GCM,data:Cm/rFqo=,iv:2AsHU12kThnxf6snTFJ5txMBxLqHtKKxXJAJvryapx4=,tag:+2Ol8nXRQq0fGCbQc4GBbQ==,type:str]
    AP_POSTGRES_HOST: ENC[AES256_GCM,data:4B+rDIEj/zxidUZ89OW0LA==,iv:3To0r+yrB+ca006SBM9y9NjyLo10bxYY5/Z16l9aPrE=,tag:rx7m0Uu0Lhr8nFpAO9LMCw==,type:str]
    AP_POSTGRES_USE_SSL: ENC[AES256_GCM,data:k1YLrg==,iv:LwpiRislLtD4Foyun7A7BxSgm1lhcoATRVGULS/Gpok=,tag:nwmG9J4/sbxlzQ+F2NCr0A==,type:str]
    AP_POSTGRES_PASSWORD: ENC[AES256_GCM,data:eKcVThH5srquTBgB0nN1dslitM/EGybt8epmuaMw5erpWBM7CYs+JYe7UjY=,iv:f5bhh5Tzr/ENjlSb0ThrFjRtNxUnsFjMS99vnlomnBg=,tag:7ookVB21FNa40azjWh24cg==,type:str]
    AP_POSTGRES_DATABASE: ENC[AES256_GCM,data:KWHEUh5Tfzy8MG9A,iv:dLkxZzcYDWum0dLKITYOgqRb8Mh+dbQ/+NugmtdJ5M8=,tag:kWSYGbn41qHlCF7Q+KFZlw==,type:str]
    AP_DB_TYPE: ENC[AES256_GCM,data:71YA9yEFLRo=,iv:gz7aVk+kAT4y0UeX5flVRhpArQOQfi6+7Tcu1b3HpAA=,tag:5Rk57TMHS+4GbKGiJ+J0FQ==,type:str]
    AP_QUEUE_MODE: ENC[AES256_GCM,data:XhAY7uM=,iv:Sqg0XkX1EZLLqRBDPdIPAjVBLFGlxA6botwpG6f7hLM=,tag:+00AWZ56YsYGlSf9ACKuLQ==,type:str]
    AP_OPENAI_API_KEY: ENC[AES256_GCM,data:/Rvm5DunB9XMC0N3prfZiMg9UK6iL81VUHSq/NwcIxLvr1KwCQ03/S+a8vNMl+ZmiVzr,iv:T8iidx/mskkXZAD/aYo9rCVlrfWUMttbUx0gwCRV6jE=,tag:Ej06T/r82UScVO/hvXm4+Q==,type:str]
    AP_FRONTEND_URL: ENC[AES256_GCM,data:MWHrg/kjJ8BxqY7NThVhGr96Dw==,iv:dEIYgrRBEn7F3vFs6x2DzvNV5ZbFRx7oMOf2fEVj8K8=,tag:SoYeEZV4oFPMOtLFaRUkDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSlhiZkllTUNWZktFYUg1
            MDBhK0RnOWhwcFMwNXZybVRhVXVBU0dmU2dzClUvZ1NQd3gxUWt1bDI4N2tUV0Jo
            VktzakJWS1FEcWkwMmphQ3BkUWZGaFEKLS0tIHRWRzRGN0JuZTUyckhidnBqY2dR
            c3pTTXJLSHNWRjhMTkZNWU50MG1yb1kKTgz0xdmm+YE0ORvhX+zNLwD2qo6cLRVb
            01HgO9GdiriyTdxAyP6jPa3z+Gi/g18jA4MZu75PTHJB8mZJJAPitw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T16:48:36Z"
    mac: ENC[AES256_GCM,data:7BPcBplAKcXezn6fdqOMcp/Z4yq36LdyPEJ6Bq8JYOugP9UHjv/2HAc4S/JKsvW7GUD90KvTZ52ztk0WcI6C6GnSQPT+HVock7TgUdEWIHg6A4uOiG3U0CACsa2AJUrx3kRsxdfOnIGnAIZIPXZMR8pK0n2pB+SPe98rsV7/2pQ=,iv:o/DevwS/SnVpMT5jNhn5EQaWqiolEKRaE2SJRlqtVEo=,tag:FF2d+/GweKNDEKt/f0fPpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
