---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonflydb
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
