---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./amd-gpu.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./descheduler.yaml
  - ./dragonflydb.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./openobserve.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
