apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:jXIpSdBsi5KaQmO64sja7NFY4yPCggdkKrgyOa19cNnnTiDk,iv:uHnW6exbfBcus0BxCUGFI4s11yOO+IHznSJ/lAJ2JWc=,tag:CCB8Tk1+CYb4jQmnDMpY7g==,type:str]
    credentials.json: ENC[AES256_GCM,data:WeuHPLpdGyKG+mnGAaUuxibPQqoXN0xFag3BGmlI1TzYe41hUSbYyWnXyhI2MIXkhGj55kC7CMQQLi89VaFXUmNk6yLyT5XJtIBKhdwEm1jVf6WUfSsW88RpY9avci6olx1BMPSgtUir12x+7+9ZrPVuQWKUP+bMjRiy+To2aH0uXOdP8bx79hNscShUUZL6R/IE8/r2sJjeNoMyvYWME/W5QeIKzGNnqZUCZC3dpA==,iv:IJAWn4o8VNG7yR2AP1VPzp5FUrcvwwjLcBIn5muW+Hg=,tag:n8czsOqfrpqWvpRS8yHIiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL2I0RThHYndrUHlCWjBT
            SERVNmRYNDNkU0dMU2U1L01EQnEvQmlYTDNRCmpWZmQwWHA4Mlc2UTNBWTN2YkdP
            ZC9IU21WeHplajdWeTBOR0JaQW9iZVEKLS0tIEsrcFBWNmR3TXkyeHZ3ellhTWZk
            ZEx0bitsWDNlenN5L2JoaFBBSUQ1RE0KVmMPgFdsymwcICDJd+vX5Pm59pFdEA5W
            PJ/Mw0F2aJGEV4R022qUzH7WrHfXjC/47WyWuvezk8IB+20gnq7eUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T21:49:37Z"
    mac: ENC[AES256_GCM,data:FtGOH9vTfRTueKsB4/3TQlwAVSqWAgPo4kFh+VVdICRw6fC1u5KACkGgbvWrRdcpBZADfj51XK3zCawvcAVmLoOYkUOKV0tgiSBgQfP8/umGEdIXJUsTc34kCidh+GHCpMRkLky9T1ti/CLPaPMMYInoIkpOV5IRgDRXyk3ox8U=,iv:h+aK3aIGyL9pkwXL8OMy5KPshhgMhZxEvqGtsPsacuc=,tag:lYBELSIioS1W0BFhEjJB8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
