apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Yp/4ad/ulTnYdMUcKz1ORvAz8+xKkQpfl72Mtaz3I/i9CA+Y3ERmZQ==,iv:ZMm9xVAK4IZ8vHafw006wH3SrhOjJhQWade0CDX12iU=,tag:/hRrrGl51yVMRHuJTFJvCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MTgxWkwyTk9hL01BWkhX
            ZzNpYmF4UHJtSXFtR1RLWnR0QkQ3YTExb1gwCmI2Vnk3RjBKNlBFa3Nxby9GYmFM
            UzN5bC84U0o2R2oyZVFSRHQ1eWwwUWcKLS0tIFJUeG0yUWVidDZvWVc2ZFRGVnZO
            K3FIWG5WNzJ2Y2NCS3Z3bVRNUlBBLzQKNXDoqRK9m9qjBEpC0/zn7K2E/C4XF4B9
            puM8F3Xoi+upUW+I/DUPCDQb6pWULgkUuckuJowDMeJWTTL1QfPEhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T23:56:13Z"
    mac: ENC[AES256_GCM,data:0cL8e5yXvFdBbSDS0nJ9652soxnpQygMTFyUTryLkuk3m2ZU6JSI+bySBEoCVvrcRMiDSkpz8KtP3KIiw6n4TRTB+2sU7KjcughovViDjogfDyfF5QWNq+M4CZnyD1IJEAaQhi5OLvf7vM7EJn0k5NLBpdh6OmrtrIOWDSA4zIs=,iv:vCu/U4I/h00qWNf3Hx9gEy4cccfedeyzCpDlje1BpO8=,tag:EVqc1ZVttI7YEJHB5K+tlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
