apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:mNEGuRjs6Pw84h1jC/yEj6l9J1WRFYJUrzUO2abkq2R2K/wLldohXg==,iv:oaXFPRVcyWo7J1y7emdUwgKfLLbHCY2otwPBWNUli+8=,tag:bOkzW4haTKqJ8rzSqNEJ4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa2x4MlVKelpJNTJNRHVo
            SW41WGNnVTRjZDltNmJvOUxaSGtZbmFzLzJNCk1DOHRrZTNxZHZaNHMvWHZhV1FY
            Y1daakU0VGpQNFFZdEw2YWdET2RkYjQKLS0tIEQ1ajZvckFCVkpHNVN5TFNyM0pG
            WGN6U0VrZ2FGaVRoeVJQV0VHVkVNUlEKFmn7aoJxSR4rVIoXLuhHe8PNCubsUbf6
            sRoNLy/aVSva/S5PAFopEU0qvq/82S9guhGsPnzjGwqx+zJTymNOcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T20:27:54Z"
    mac: ENC[AES256_GCM,data:GUL1ow8KanxrrL3yYcSDkV6xXYIyn8lpSdjW33U88AnATwwPeCUGAgV7Y39alMGxlOe9fwT8SxBQKdFjYtpWxB8zp4ugIf0/X1APmjphFtzPGDCi/3MHo2pKBcIobeYDQC6kumIQBOJO75/BFKuzgYhyqFUVYVAR+L8hMzCCGB8=,iv:0rCW9QbS5hUBb7qdy2goEOn2kRDgL8uqtNjqfxwwDEs=,tag:BEpEUURWJ4ih0j5XxYj9zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
