apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
stringData:
    SPACES_KEY: ENC[AES256_GCM,data:nW95sUk0RXJFfg==,iv:PQORzomzBOT+uFm2Jmpu+WNZmD6ai5wlqfjNvIJPiIc=,tag:+k+6i9vtjNoKCn4F+Z6kmw==,type:str]
    SPACES_SECRET: ENC[AES256_GCM,data:0379zPdV/vgxoMetXw==,iv:PlCWwmkMzGOHt1F7GPuDhGuGCUHQmA1I/mcXdlPZq3s=,tag:5fHeqztePVrNFUlNv5lZcw==,type:str]
    SPACES_ENDPOINT: ENC[AES256_GCM,data:DHNtYAQYJB0b//LmUbSeHIZG,iv:ssIgfcmLAMagkizjgtVW8jyVz4UuGkAVwPWYId2kcCU=,tag:NJaeqtcvnKtmiCMvtDW7Ng==,type:str]
    SPACES_BUCKET_NAME: ENC[AES256_GCM,data:fxosOoiutG4AHg==,iv:ulzwbyUQKltiCB4b/NWvX4VCLccEeccW27N4b5i2Ic8=,tag:fCIZ43LMrRryRLZiAdewJQ==,type:str]
    SPACES_REGOIN: ENC[AES256_GCM,data:dozjDIMnZM6f,iv:2+CKqQEfHcE7B8ZpFqpRGZ7iStV2e1lWugKYVrCz0UM=,tag:DjzZz5cn8BvUJeZ5qqhbiQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:1udJcV6PGIQ8eJCOxY1c2O27JoCleXiwSRPTttFZF8f0uT6FmheiHYD7dI0=,iv:mFl0FnFFBOELGeev717ZYMjTDfBMS4RNfjSKE1WUGLU=,tag:q457lueqa80/DgmponEnmg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:j9sUkMznWnP1vNS36AkcK8ml9PmPag65fRlxhk59sc3FMHNPyMr0IK82S0claCRnsbpxEtXKTp+V5ayiOSuo+xulpoJToNrtE4uwFoKeUc8Q2Nic3GTphGz5ZAJPhoR5yttJqGel6bzWqejh9qc8TIEBS5VnmQBb64u+bH5sxfb0rn79aSN6Wo2NSA==,iv:5u31iFqnBcGFCcRa+OOePXZnT3v9SW3R7EqTQbRGv/0=,tag:/d12DCVfNhQOhP9PNpl+4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TUNJeGZDZ25hb29wK3JH
            NGNBWWNabHdYQUtRUHVPTmFlQUNnMXZ3SWpjCmJTK3BvSnIwaFZaMkErVzJXMEFC
            elVYdThmUEk2WVBNQ3duUDRBRDk4SVEKLS0tIGM1TWJwWmNVMnR5eFVXNVF1SXN1
            SDZTL0hNejliNUgxRVVuZ3Eyc2dzSzQKWmqYAkrmJeKHvdwpn+7xZbkc28R8KjA7
            zfNhATU+MjOvGeQlHZHUVYQmpyNqUlWK7BxhQUQ+WQZwXNmkljTgCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T16:33:02Z"
    mac: ENC[AES256_GCM,data:p3A50c0o9lctCFN2RB1w1UTs1VBPMjjZxKdrZSmUlT3qEjGZTAt06a/xmEgrAx+f9w24o/SqCQ+PSbhsEmqN9U9mNSMRu3vWLI2dcWeFsHoB1XW8LSrlqeDOPF/lUYSKmIyQNW/QL1mljsXJTOAyW6eS14TjiLBMi0t9Jwq/aiA=,iv:y5YbQDYRg4gsH7mLQ0nH5GmZWvhGbof8F/s8LFX00Ic=,tag:f2oomYHyDOV7L9/GgRJsRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
