---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  # - ./o2/ks.yaml
  - ./unpoller/ks.yaml
