apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Sf3SQHsCsg==,iv:jh9wOw180xiXUJIHPTk2kKowWif78pfV+en6tiV2kh8=,tag:9s8YR1PmQiYkya1ZQF3Yhw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U3xHW0oIzX9i1XCxKHgMlBihD0gVWKKYUrs2,iv:acJri0boNb+vFHCZpjhCZW2/13XvJF42cDkbHX/v+W4=,tag:UNgOPq0yo7+Ag+DB+/IqHQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4em5PTGw5MTFmblhhbERI
            TnRNdXVzN3hDdGZHMDlpQStDaFBnbVBXWm1NCkJZT2NmYUFTdUVBSVN1OG9KUXpx
            b0o2NG1OeFIvNU5kY2s0QThnemJON2cKLS0tIFB2N3FsT1A3T28wOWVHWHNuZ3dv
            SkJWSzV0TXF0bXBnVDZJV2RXNDRodmMKfgsgp78bVzktR/7UdqO0XaNWr3xOvenf
            E7hfrZ09xCT/i4EaNEk3r1WUi7/gF6h54ffzMxaMPU0NHqIkmMKjzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T22:37:01Z"
    mac: ENC[AES256_GCM,data:9TM2/iORGm0r4OnmJgiR0S/v6FqXWzoMOiapwFVQROogAFzbUDl90RLM5KLAcMwgRCJ5nTg9rdK2A+TsgnsmgMBV6qrTRfiwacBPSBkzSx2qFArC5kgdK9NMX/9N3nNbm0MD39qAJWe1NvhQDEmfscdlm+XROJKEuvgPDXVQj9E=,iv:yDElLnyVaXd9P8l7ma+V8vm6G9avFQaMIyMAD/PyOXA=,tag:4/v9U8GgCR4lmToTAInhuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
