apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3MHBO28S4g==,iv:lqZWGfRqkf2WU02uv6Ys5KTZv3RMb6u/TXQzpjlhUfI=,tag:XMilQ/Q2Q0jXbsyA3RpmJw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:32KrhDPxRhFL7nlPZWjOJkf/ROgXDAk9A3Xi,iv:AazDTsQFt8wjlaiNumPN5IQgsS92cjVGr8IfmKAN89o=,tag:uF5CXoIyc+OS3RlJmQAgqw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KPHAuOb204UaFsm8bA0hqEpup03gAbQ16FduX+upB/bWw5VU,iv:0/fwdh2d6aO058AqOILP3uAaY+PzzYpaCAxlfh9O0dA=,tag:75qQHjzEMxUG5vIfiksGAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Zk82cUN0UlJZQmx6aU1L
            ZkwxY2pVQ3F6d2l4TmFEU016YTJodVhUVlZJCjNmakJrRGxoVWpNbnVHb2JkNTVM
            RWtrVmVnVG9COFhZSXlZdmlRVXh1THMKLS0tIGNUVFA1VVN3aytiaWlRM2FrYk5G
            WVM1Vy9zZTV6dEdHRW0vN1pYUzRUTlUKnlkDAiBJf/8zDyJMCETdfO7xf6UXDPl0
            dvbKmT4s7ihbWswv1TdGPK/x7qvyjBiny3+YiVrtty5Zu/nAM7eXZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T13:53:43Z"
    mac: ENC[AES256_GCM,data:jva3KEVe1ywx1bCEXa8+2CgJPqU4yP0By0aSZcaOeqKsgv/QuxeMuoDOXMh8l9L+nUH3mHNItQKfwdpkwZY/BuKILb0+WfODlf1Kdx4uYjX0wocnqJQEFqDujjBDnIe7tLdiXuiMoEuAA9+7Ly6YoXUQ4CT2Z3WpSge8+tANTFk=,iv:kRYFrvOwtCBtaSkEnKS4qxQSPwRpVqJHOG9H7zKGPhs=,tag:PkbCuUZlFczubJmw/0hPgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
