apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:d74YaeT4Yg==,iv:VjY2kQ/IiS2dSOlltjaOEIoTihbIKbjVDVo93Hq0eqs=,tag:hhoHpXA6Z72z/n8wJh+Hrg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:X18u++KKs2rYV/W0rlqOxzzpzcsrlB06MlJl,iv:/lGoIQ8Zhd2pbp3itTH/0yYVhBIpDXm8HpeNrK7nWy8=,tag:jphS7xozJoeGC7NC3kfCWw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9+pHnKNzxxP687k04Kdod7zfjRETFO6HWoJrKpw1T6XSkp1m,iv:z7j8ov6FsTvvXYpgkduLdapF2NpHdeJjrbFcpWHbFzk=,tag:TiF9Ym2PrUfapYB8fm8FGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQjZqNmlwVGM3eWtSUThM
            NWFXTDFjWmdUaFhmK3NYN0cvdXJjYnFrOGhjClc3c3JwVHZGWmNmUi9WOFppWjNt
            UmVEZW51RmNBOTA4MVlQZk5hYTdPa0kKLS0tIHg1S1hBUUd2OE5RVnZldFducEQ2
            eXFDbDRmaTVhVmtTcEZQM1JHVVQvUFUKLiPpW9azbH5LRPqQGZVnvn9n/0FRF2wo
            BgDJ+8C92cJSiqXa7ykzl4h0Y78un1hbY9LY6DCz5hVPTntxxH38eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T14:56:23Z"
    mac: ENC[AES256_GCM,data:VDWZeVlMQ8iUIQzWrLt+2K32rHtRZh7NXZ2mTc+eGWbZetaA9HA30mdqZszltzVC9KtTIKwTGPi9qjArtLR+kVFAuN09NSK4MVmRNgK4VbRNh5DdpB0SVOUjPna+MlMbF03reHH2Ca3WmNQ4aj/GESqQy+oZdnTWt50PUxCnmdg=,iv:qZCtykATVgAK0hOTtpwqWkOL37PmyBGRrKU/BBiefKY=,tag:CGGP9eX22A+PtvTzJdl1CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
