apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:RFS8fjd4BQ==,iv:MyG0p909NW9aw2pmN9pf00nb4Fi3boxO85JZneyyLZc=,tag:YbfyoXXLk9HQ6mGgYFvRsQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oHXbWhj0i0wA2F/XEQ9LnhWMfhYsEyPuysBs,iv:G+u4xtUKfUOaUl+7xv5bCnSK6u010bdcto1MxZ7mg6Q=,tag:ZfvHZRv7zRmf2fgCZ3UhLQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSUlVMHNuTW12YmxLdW1u
            ME45VytXV0JZdTMrdnpNWVpBd3JvN3BYWUNZCmhNcnk4TW93dzBmR2tqUEdLSFpG
            eGcwWFFqZlhIZmNoWUE2V3NqNDByUzgKLS0tIEdleTB1UWtZdXBFaTdJMlg4alRJ
            K3hIYXA0Mjk3cXFPdHdjQ3hpdjhUSmMKMAZUXU5KifzsuvehEEO4vd85exHcksY5
            JXdJgYjta6C87k1Un5J+EgzWkd+xK6eSkiaFW8ynAHSvBwyXMZKALQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T20:27:54Z"
    mac: ENC[AES256_GCM,data:P9ZFYuMcTaQSB9ZhjJFUUeB5LxiHeJylY7+Mk74VQO6VDuFPATCL6NHTK+EDWrQDcTaBJSor/HixEh5AKzCLz8JW4kfjDNeMIXGBLP1aa0wJLt4KJITor5tw+rbdw6HZ+qZxaJpkkEHYrHaqxIR1T95ElLFmkrPkm/Xl05SaIgA=,iv:r46nEOsV/fup1ktT8JVtYHmOjey+oxz54Nk6n9SZTHg=,tag:TK1hyraJWlAcpzShw1g1Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
