apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:QfLufy6xaw==,iv:UVQFbhOzIvlcaJcfV1d+Unc0DjVpKSY26/IA+Sxg7Ug=,tag:kmvLJXcCoLMETsNcAM1ZJQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mFnCPjIqg4kL+PrOa9aVoersPjhYQAv8BKfo,iv:6Lnsc+6WOacA9acIeyATNpEOWpTVn00QKn6D+o5t9mA=,tag:canpRfCdhIQwLgvTifrxIA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOW9CMXFqMllDbnlTQWRh
            NHBRdFJVQmg5azQ2UHUxWTNYU2hsVlF2TVZzCm9WMUZmbWRackUwTWd5WFZTWVds
            MFp4TSs1UUx3dlF1bUIyKzB2V2w1czQKLS0tIEl2S0c5TU85REdMRnhhZ1hKcG1H
            YXdlM3pRSzk2cjUwNnpOZjRyWkNYdHcKWOS4G+O4vIdQjMBqsI9egDvrlmbLPwz6
            CCHr5+L90RaWdhiuoNem+8o5UDo+eUeLySQAp57xLmS/L1omfrMTDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T23:07:00Z"
    mac: ENC[AES256_GCM,data:eWdGh8T/Ibyd7oohLdrFVqDGT9CgW3UluufNF0nZUW044g8fTNL6kxBj1fICaWOUFAa3MJ63ej21BWApi3IpTebbuWRKdjkjkyzZ+O96o588AGWFSsgWK+2MNd9fs6yuviQfuEwwCBlLShTPjdGiSp84zP4mqR5NCxbkuCYiNhA=,iv:/yn01bwDh/Ur0VgkzfmrstSWEVbqiKbbm+ONXVAspp4=,tag:iIL/86EDJdsGydR60Fdd9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
