apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fMhqAfRDew==,iv:jOeZTswiwdFMpzKrIcQFuEOoDPNEhqhQYbckjPGs9AU=,tag:1EOIokLi7N2Kh+bp3h1Neg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+lqPFq3luzQjVMXi0ibZWeVOTNqky+b2s0wM,iv:XvfARrX3C9cowJAwecS6oCkVkSwGcYeeG67dEbrpfqw=,tag:2ffboW/H4Ppn3qPdwwFrag==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:j30/EX8p+/nVj7QMcyeuElzOlQdcIITAw439itBdRGx9er2o,iv:weHFBqRcyEm4VpQJmrPTZ3Ltclj58ZL18pfTF/yqf8U=,tag:Hu9mnNholEMzCwxegqH8VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxckZDS1FJVG0xVjVpUjZP
            UkpRMkszK21nYTV0UkZ6NFl4OUpGa0lUcDIwClM2QXJOU0w2UTB3UHRiRmFEVkdP
            Yy9CeDRmMnRUR3NHUHg2MXZudStXMWMKLS0tIERVRis0QVZscEZmemFiNk5jbzZv
            TDJWaVV3Z0ZybmFRejBWU25TTTdXRWMKSDTaeBj3NUj7Mo8voNP/ldf9x9ywALgv
            0yrnDcSstsU8lmZzENFI5130MzI3m7KyMLYkE1UW0rP+6oVSTNT8mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T18:31:41Z"
    mac: ENC[AES256_GCM,data:iuoeuWRb1hwJpkNTlzBbUR83Wqknk5O19BwPTolcYGk+8e618mpJC/nhPtCib59bqp7PmSEaVM2TMewdTQgxdR0fyMD8xRlzqdjMEPbR+CGFl3nnaDC+jFVQWUnfjRAzJULP09xBtHBfgfYq8k4AyCja6n+Byl0KdldCQXODndk=,iv:QChmSuhXeA1pd5fGrDf2Km5HcOFW8br8oU/4Deay1rE=,tag:alpZ2OSuYvWkTMnaHGvQFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
