apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fA/rxMGB8g==,iv:fd8dfCOAHQeFSNShL2mfrkEUFpUKBeabdy8zVzhdjrA=,tag:YwsyKTI3KwuarF0gdGg4IQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1+SoulNk/r8G3lQFaoJvrswOl9yiYtdZah0l,iv:zGpPyzhG24ucU0RVMSqHtCNqMRVRoKtGuz3ITiuN5ik=,tag:cy0CCvlU2OhbRY78ji4uTA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYelg2Ym8xb1lUNCtuUjZJ
            OWRzWWNSK2xiQWlPVzlmSmxiYmtpa2dSS0hjCnhHM2NTc1Y0c2RLdGlDeWdNWDJ1
            YlNveWtsTDEwK3E0dVZUV0dwaHRhd2cKLS0tIFMwQ0h0clpidUUvTUVNRDc5d08y
            RFBWdEJmSndTTzdPaHVGV0J1enB2ZmcK1BsCufrmdeFO4RJA/a+Ei4XXHCJCVKLw
            5vtVUn4UL5oQr8aD4h1ZW1IO37PFZzW/up+C42btyTVl5U1R+/HHfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T23:56:13Z"
    mac: ENC[AES256_GCM,data:S7kEDyRLsrTnBdmfIsou54Akh03MzoIy5rMrXg6dmRZ7qA5LBqw4oR32wnZ+dwxAkY8vYrSeS5326r2OhNDlf1TWAsaH+JSXSRTWemSfyPfcJxed1U3c98h4FoCw0GQqS1ryMIDXP4ouFyi+MqZiBUHXsuJNALYRxSaQ3DyckP4=,iv:iScQf++uLRsS/33VdQXa6loJHeXfPSNieU1c+QvkLkI=,tag:6GNv04f01u92XFRthluevg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
