apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cqM8HTNH0Q==,iv:9BF38BPr0KIDDWCmyxu6GILKFDWqEZ9k/SDuml4bn5w=,tag:4ndnaDtoqUQ6f6SNPVb/Bw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DMuZzBLXjpqsi1kb5LGZ+b+3E+0sxUPM2nKN,iv:QEelBf91IPtqrWBXg/sdENfwXGtoUzZ6CAahiXE/KPc=,tag:Vp9LFYbC/TLm88TgxwNFkA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:UBUyQ3aBCQhiqYKngUL1pI12GZNSa/QnCyqgYZOlxnIGwKGN,iv:/03D6dv2bcxurorfBVqUIP1HA+myvkx/VzRX6w/Gdak=,tag:Ly3lOzmLAL1QcDsp08r+Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ1hlN3lrcE9ERkFNbHp3
            ZTFxS3FzTDB3cmRIYURlaitQaUxjeERBZVJBCkxDRjd0Um5LbW1Ybm40bTNvSkJY
            TlQ4UmtLVnR5ck1KemRYeTN3TjBoNmsKLS0tIEh0QU42RlRGN2RVNzI0MFZxMUw0
            dGxxc2IrZXE2em5zajJGYzgzdzR3Y3cK5iKU5kySd++Gpeb1i8/kW9mbHO3bJh+P
            YcfdddgzFQUPp5bJcU/kvXe4nlXe0ngBBckEc6TZZ0U4Y/JW+4+6Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-13T22:11:31Z"
    mac: ENC[AES256_GCM,data:X+cEpc0GJ8IfYoh3tUVmfnFgyscqKgACa5q2XXkFm/1UAXCuKZjMTT5+nlW9v6476A92btOg11869gCU1uT+/KyH4Zxlf4X/hgmfmsu3BCEyGAOjku9mx+9L9KhFQQTLrM9G3jgJNH4Y0O5qMNp3xi3ifx6G/uyvoo0Q1wuNJtA=,iv:zwuvk/2H7WK6SyEfKa5mfJgPk8FWBqgFoxUbBRmYn8w=,tag:JTwCLyVP9xE4FizRnFuW8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
