apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5SrV7DTDrJgNSYd/XcpVh/SlfeVNBRp5iEloxa/5mGc=,iv:sUJheIb9hpYCI4RJPUyc+o/p3dHY75dzbPdQUllxalQ=,tag:6/BJyvn3BQIB7JLOKrq2uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyblQ2cXBwL1F1M1BLZWsr
            VHVYY1BtdXJPV0I0bmtlMGJ4WHBBSFBxM3o4ClprY200d1ZTQ3h4SkZaTldmeG5p
            RjQ5VTFMcklhY2tnR1lRMGQ5UXUrTk0KLS0tIHh5KzNLK2lWOWwvNy9CaWxMdHEy
            SHA2UWt5VVR5akRRdE9aQzhLRVJ6aTAKw7X94JOeyLIOM/A6IQf40adjPTkKBQy9
            cRnXefCZZVa+UjCq4kkR11PSm7PTSwURxGeX87dtoTlUxtxFTOSI5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T22:37:01Z"
    mac: ENC[AES256_GCM,data:Xw778Hcha4N4LCZwBnyVfM7TOnqRKsuyFr7aJwGJ+BKeU0RQVnjulp6bIGNuv465L3bwLNN6/nlmbQr51nqjnAtGkBchEoCXngsVy/eVsnfxwmWndzJQ2QwT+Bgy3iSY0+CpeOBiV2NBdIbdeemuPfCY5AhY1KlnLP9OeIuOX+o=,iv:KkNAw/Exd+FNnMxsDfvxoWwWCctz/+t0MVm1BUVioG8=,tag:TRkKLFJE9JuBLiAjkj2oHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
