---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: 9.0.322
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: reflector
