apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:J0ORCTc0bNhLWfHbD5nnOlnBUBg9xnU/L+zElgRA7ZT6BjK2kiVCRw==,iv:aK+sLelkybhA75JXlSOGBEnBUc3XrQY8ZqXp4Y8Xf88=,tag:f2+e4UCupo/EdEiEm6U9nw==,type:str]
    CF_ZONE_ID: ENC[AES256_GCM,data:C0tHHID0GowhyPEQzEeIwMR3Gp01CogjSjJBdN+8Hqw=,iv:FFADN/aXxPDYKM2aknXFLOQ462CH/CDqTJ+RGxmbE+A=,tag:KwQ5smEFJ9RHiUguxo4fpA==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:pLv1VFRWEkvONTmsrmmqgqsohK4l2mgJlxCLTwHV3I4=,iv:Tg1YXlfpxMSx2P9/ygQBe1otszFSkTkWTj3RVOgF1Ps=,tag:J3btKAyCfmzVjN7RIYbt6g==,type:str]
sops:
    age:
        - recipient: age1qwwzsz6z2mmu6hpmjt2he7nepmnhutmhehvkva7l5zy5xzf08d5s5n4d6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTE5MNWNPYUY2TUVQOGZZ
            eGYzanhxK3dxMERwb3RQcHpuSUhPQVdVRFhrCm5TMVV1Wm1GR3NQYkg4b2hpbFIr
            RVRmMzkwNWczc2duQVp1eU1oOC8vbDAKLS0tIGQ5d3NLQmdBTXlubThWS002TVEr
            QXIzNmJBM1R3Z1RnSitadkhRcy9lVkUKOfowwhnMSfKgMEm5b2/9TRv5IZMd1bH6
            9nwfaaqpqQM+QFTn+Zi/upH3LpEECvzde+XyWZIzlj6NA0evXJhj0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T21:29:16Z"
    mac: ENC[AES256_GCM,data:t8ov3t/Tq4sMlIb7SECJgvDPge3fmofPyojYs8DtE7ueIQh4Sh1bsOMXwiw1SKGe13W3ZR157JA42zmom/Y8nbiVwNrBMcKgBJWRd4G9lQ7ZDH8v1DMW0dcq0aU8faPDwn5kr0Iue3RPAN+otA9HSbaJPJI8+4EkIsKzsL6fqx8=,iv:E0STavAWCpfTQlz8hulkTiPMEtBT52ACF94R8+Agd/4=,tag:435dAwlT0zRcHjwU53cE/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
