---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    logLevel: &logLevel debug
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.5.1
    env:
      - name: UNIFI_HOST
        value: https://192.168.35.1 # replace with the address to your UniFi router/controller
      - name: UNIFI_EXTERNAL_CONTROLLER
        value: false
      - name: UNIFI_USER
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: UNIFI_USERNAME
      - name: UNIFI_PASS
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: UNIFI_PASSWORD
      - name: LOG_LEVEL
        value: *logLevel
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    extraArgs:
      - --ingress-class=internal
      - --ignore-ingress-tls-spec
    policy: sync
    sources: ["ingress", "service"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
