---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: o2c
spec:
  interval: 60m
  chart:
    spec:
      # renovate: registryUrl=https://charts.openobserve.ai
      chart: openobserve-collector
      version: 0.3.16
      sourceRef:
        kind: HelmRepository
        name: openobserve-charts
        namespace: flux-system
      interval: 60m
  valuesFrom:
    - kind: Secret
      name: openobserve-secrets
      valuesKey: OTLP_AUTH
      targetPath: "exporters.otlphttp/openobserve.headers.Authorization"
    - kind: Secret
      name: openobserve-secrets
      valuesKey: OTLP_AUTH
      targetPath: "exporters.otlphttp/openobserve_k8s_events.headers.Authorization"
  values:
    exporters:
      otlphttp/openobserve:
        endpoint: http://openobserve:5080/api/default
      otlphttp/openobserve_k8s_events:
        endpoint: http://openobserve:5080/api/default
